src/AppGuarderia/urls.py
from django.urls import path
from .views import bebe, niniera, comida, buscar

app_name = 'AppGuarderia'

urlpatterns = [
	
	path('bebes/', bebe, name="bebes"),
	path('ninieras/', niniera, name="ninieras"),
	path('comidas/', comida, name="comidas"),
	path('buscar/', buscar, name="buscar"),
	
]

src/src/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import inicio

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', inicio, name="inicio"),
    path('AppGuarderia/', include('AppGuarderia.urls'))
]

src/AppGuarderia/models.py
from django.db import models

# Create your models here.
class Bebe(models.Model):
	nombre = models.CharField(max_length=100)
	edad = models.IntegerField(verbose_name='edad (meses)') # sólo meses
	vacunado = models.BooleanField(default=False)

	def __str__(self):
		return self.nombre


class Comida(models.Model):
	nombre = models.CharField(max_length=150)
	cantidad = models.IntegerField(verbose_name='cantidad (gramos por bebe)') # + kgs

	def __str__(self):
		return self.nombre

		

class Niniera(models.Model):
	nombre = models.CharField(max_length=150)
	edad = models.IntegerField()
	años_experiencia = models.IntegerField()

	def __str__(self):
		return self.nombre

		

src/AppGuarderia/forms.py
from django import forms
from django.forms import ModelForm
from .models import Bebe, Niniera, Comida


class BebeForm(ModelForm):
	class Meta:
		model = Bebe
		fields = ('__all__')


class NinieraForm(ModelForm):
	class Meta:
		model = Niniera
		fields = ('__all__')


class ComidaForm(ModelForm):
	class Meta:
		model = Comida
		fields = ('__all__')

src/AppGuarderia/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Bebe, Niniera, Comida
from .forms import BebeForm, NinieraForm, ComidaForm

# Create your views here.

def buscar(request):

	if request.GET['nombre_bebe']:

		respuesta = f"Resultados para bebes cuyo nombre es {request.GET['nombre_bebe']}."

		nombre_bebe = request.GET['nombre_bebe']

		bebes = Bebe.objects.filter(nombre__icontains=nombre_bebe)
		
		if bebes.count() == 0:
			print("coca")
			respuesta = 'No se encontraron bebes con ese nombre.'

		return render(request, 'inicio.html', {
			'nombre_bebe': nombre_bebe,
			'bebes':bebes,
			'respuesta': respuesta,
			})

	else:
		respuesta = "No enviaste datos." # crear template basico "no enviaste datos, volver"

	return render(request, 'inicio.html', {
		'respuesta': respuesta,
		})


def bebe(request):

	lista_bebes = Bebe.objects.all()
	form = BebeForm
	mi_formulario = BebeForm(request.POST)

	# Devuelve template con la lista de bebes

	if request.method == 'POST' and mi_formulario.is_valid():

		mi_formulario.save()

		return redirect('inicio')

	return render(request, 'AppGuarderia/bebes.html', {
		'form': form,
		})


def niniera(request):

	lista_ninieras = Niniera.objects.all()
	form = NinieraForm
	mi_formulario = NinieraForm(request.POST)

	# Devuelve template con la lista de niñeras

	if request.method == 'POST' and mi_formulario.is_valid():

		mi_formulario.save()

		return redirect('inicio')

	return render(request, 'AppGuarderia/ninieras.html', {
		'form': form,
		})


def comida(request):

	lista_comidas = Comida.objects.all()
	form = ComidaForm
	mi_formulario = ComidaForm(request.POST)

	# Devuelve template con la lista de comidas

	if request.method == 'POST' and mi_formulario.is_valid():

		mi_formulario.save()

		return redirect('inicio')

	return render(request, 'AppGuarderia/comidas.html', {
		'form': form,
		})

src/src/views.py
from django.shortcuts import render
from AppGuarderia.models import Niniera, Comida

def inicio(request):

	ninieras = Niniera.objects.all()
	comidas = Comida.objects.all()

	return render(request, 'inicio.html', {
		'ninieras': ninieras,
		'comidas': comidas,
		})

src/templates/AppGuarderia/bebes.html
{% extends 'base.html' %}

{% block content %}
<h1>¡Registra un bebe!</h1>
	{% if form.errors %}
		Estan mal los datos revisar
	{% endif %}

	<form action="" method="POST">
		{% csrf_token %}
		{{form.as_p}}

		<button type="submit">Registrar</button>
	</form>
{% endblock content %}

src/templates/AppGuarderia/comidas.html
{% extends 'base.html' %}

{% block content %}
<h1>¡Sugiere una comida!</h1>
	{% if form.errors %}
		Estan mal los datos revisar
	{% endif %}

	<form action="" method="POST">
		{% csrf_token %}
		{{form.as_p}}

		<button type="submit">Sugerir</button>
	</form>
{% endblock content %}

src/templates/AppGuarderia/ninieras.html
{% extends 'base.html' %}

{% block content %}
<h1>¡Registra una niniera!</h1>
	{% if form.errors %}
		Estan mal los datos revisar
	{% endif %}

	<form action="" method="POST">
		{% csrf_token %}
		{{form.as_p}}

		<button type="submit">Registrar</button>
	</form>
{% endblock content %}

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Web</title>
</head>
<body>
	<nav>
		<li><a href="{% url 'inicio' %}">Inicio</a></li>
		<li><a href="{% url 'AppGuarderia:bebes' %}">Registra un bebe</a></li>
		<li><a href="{% url 'AppGuarderia:ninieras' %}">Registra una niniera</a></li>
		<li><a href="{% url 'AppGuarderia:comidas' %}">Sugiere una comida</a></li>
	</nav>
	<hr>
	{% block content %}
		
	{% endblock content %}
</body>
</html>

src/templates/inicio.html
{% extends 'base.html' %}

{% block content %}
	<h1>Bienvenido a la guardería</h1>

	<h4 style="background-color: darkgrey">¿Quieres buscar a un bebe por su nombre?</h4>
	<form action="/AppGuarderia/buscar" method="GET">
		<input type="text" name="nombre_bebe" id="nombre_bebe">
		<button type="submit">Buscar</button>
	</form>

	
	{{respuesta}}

	{% if bebes %}
		
		<ul>
			{% for bebe in bebes %}
			<hr>
			<i>Bebe:</i>
				<li><b>NOMBRE:</b> {{bebe.nombre}}</li>
				<li><b>ID:</b> {{bebe.id}}</li>
				<li><b>EDAD:</b> {{bebe.edad}} meses</li>
			{% endfor %}
		</ul>

	{% endif %}
	



	{% if not respuesta %}
		
	
		<h4 style="background-color: darkgrey"><i>¡Estás son nuestra niñeras!</i></h4>
		{% for niniera in ninieras %}
			<div>
				<hr>
				<b>Nombre:</b> {{niniera}}
			</div>
			{% endfor %}

			
			<h4 style="background-color: darkgrey"><i>Comidas sugeridas para esta semana:</i></h4>
			{% for comida in comidas %}
			<div>
				<hr>
					{{comida}}
			</div>
		{% endfor %}

	{% endif %}


	
{% endblock content %}